# ================================================================================================ #
# Site Configuration                                                                               #
# ================================================================================================ #

baseURL = 'https://rapture244.github.io/'
title = 'Ovidiu Pascal'
languageCode = 'en-us'
theme = 'hugo-coder'

# ================================================================================================ #
# Markup Configuration                                                                             #
# ================================================================================================ #

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Allow raw HTML in markdown (for icons, custom styling, etc.)


# ================================================================================================ #
# Theme Parameters                                                                                 #
# ================================================================================================ #

[params]
  author = 'Ovidiu Pascal'
  description = 'Software Engineer in Operational Research'
  info = 'Software Engineer'
  avatarURL = 'images/avatar.jpg'
  colorScheme = 'auto'

# ================================================================================================ #
# Navigation Menu                                                                                  #
# ================================================================================================ #

[[menu.main]]
  name = "About"
  weight = 1
  url = "about/"

[[menu.main]]
  name = "Projects"
  weight = 2
  url = "projects/"

[[menu.main]]
  name = "Open-Source"
  weight = 3
  url = "open-source/"

[[menu.main]]
  name = "Publications"
  weight = 40
  url = "publications/"

# ================================================================================================ #
# Social Links                                                                                     #
# ================================================================================================ #

[[params.social]]
  name = "GitHub"
  icon = "fa-brands fa-github"
  url = "https://github.com/Rapture244"

[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin"
  url = "https://www.linkedin.com/in/ovidiu-pascal/"
